# Set the amount of health players have the first time they join the server
# default = 10 (5 hearts)
health_on_join: 10

# Here you can enable or disable stock items
# Disabling an item also disables all the
# item that have it in their recipe
# true = enabled, false = disabled
enchanted_seed: true
enchanted_cobblestone: true
magma_rod: true
melted_sugar: true
enchanted_bone: true
enchanted_string: true
enchanted_silk: true
enchanted_spider_eye: true
enchanted_copper: true
enchanted_iron: true
enchanted_iron_block: true
enchanted_gold: true
enchanted_gold_block: true
enchanted_diamond: true
enchanted_diamond_block: true
enchanted_netherite: true
rune_shard: true
knowledge_book: true
portable_crafter: true
backpack: true
multi_tool: true
stonk: true
vein_pick: true
severed_drill: true
mended_drill: true
treecapitator: true
replenisher: true
ultimate_bread: true
meth: true
aspect_of_the_end: true
healing_wand: true
explosive_staff: true
lightning_staff: true
damage_orb: true
ember_rod: true
midas_staff: true
the_executioner: true
venomous_dagger: true
vampires_fang: true
throwing_axe: true
shadow_fury: true
blue_zenith: true
real_knife: true
caladbolg: true
mjolnir: true
short_bow: true
explosive_bow: true
soul_bow: true
grappling_hook: true
hook_shot: true
fire_talisman: true
reforge_stone: true
recombobulator: true
zombie_brain: true
undead_scroll: true
lucky_foot: true
purity: true
auto-recombobulator: true
slime_boots: true
spring_boots: true
farmer_boots: true
midas_crown: true
shelmet: true
speed_helmet: true
speed_chestplate: true
speed_leggings: true
speed_boots: true
protector_helmet: true
protector_chestplate: true
protector_leggings: true
protector_boots: true
fire_helmet: true
fire_chestplate: true
fire_leggings: true
fire_boots: true
cheat_code: true
