name: CustomItems
version: '${project.version}'
main: davide.customitems.CustomItems
api-version: 1.18
authors: [ DaviPlay ]
description: Custom Items...
depend: [ ProtocolLib ]

commands:
  customitems:
    description: Opens the plugin's ItemsGUI
    aliases:
      - customitem
      - ci

  giveItem:
    description: Gives the specified item

  createItem:
    description: Create a new Custom Item

  setHealthMax:
    description: Sets the max health of the player

  setSpeed:
    description: Sets the player speed

  setReforge:
    description: Sets the specified reforge to the item in hand

  viewRecipe:
    description: View the recipe of the specified item