name: CustomItems
version: '${project.version}'
main: davide.customitems.CustomItems
api-version: 1.18
authors: [ DaviPlay ]
description: Custom Items...
depend: [ ProtocolLib ]

commands:
  customitems:
    description: Opens the plugin's GUI
    aliases:
      - customitem
      - ci

  setHealthMax:
    description: Sets the max health of the player

  setReforge:
    description: Sets the specified reforge to the item in hand