name: CustomItems
version: '${project.version}'
main: davide.customitems.CustomItems
api-version: 1.18
authors: [ DaviPlay ]
description: Custom Items...

commands:
  customitems:
    description: Opens the plugin's GUI
    aliases:
      - ci
