name: CustomItems
version: '${project.version}'
main: davide.customitems.CustomItems
api-version: 1.19
authors: [ DaviPlay ]
description: Custom Items...
depend: [ ProtocolLib ]

commands:
  customitems:
    description: Opens the plugin's ItemsGUI
    aliases:
      - customitem
      - ci

  custommaterials:
    description: Opens the plugin's MaterialsGUI
    aliases:
      - custommaterial
      - cm
      -
  giveItem:
    description: Gives the specified item

  getStats:
    description: Displays the stats of a custom item

  createItem:
    description: Create a new Custom Item

  setHealthMax:
    description: Sets the max health of the player

  setSpeed:
    description: Sets the player speed

  setReforge:
    description: Sets the specified reforge to the item in hand

  viewRecipe:
    description: View the recipe of the specified item

permissions:
  customitems.*:
    children:
      customitems.admin: true
      customitems.gui: true

  customitems.admin:
    children:
      customitems.create: true
      customitems.give: true
      customitems.stats: true
      customitems.reforge: true
    default: op

  customitems.gui:
    description: gives permission to open the guis
    default: true